import { useState, useEffect } from 'react'
import { SUBS, getBhoolStats, getDisplayLang } from '../../shared.js'
import { apiGetMastery, apiGetPendingMuqabalaBattles, apiGetDailyContent, apiGenerateDailyQuestions, apiGenerateDailyBrief } from '../../api.js'
import { li } from '../../i18n/index.js'
import { Lightning, Fire, Brain, SunHorizon, Sparkle, Lightbulb, CheckCircle, DiceFive, HandWaving, Plant, Circle, Sword, Flask, UsersThree, Bell, Notebook, FilmSlate, MapPin, Sun, CloudSun, Target } from '@phosphor-icons/react'

// ── Bhool Curve stats (reads localStorage) ───────────────────
function useBhoolStats() {
  const [stats, setStats] = useState({ overdue: [], soon: [], fresh: [] })
  useEffect(() => {
    setStats(getBhoolStats())
  }, [])
  return stats
}

function masteryColor(pct) {
  if (pct >= 75) return '#00E5A0'
  if (pct >= 45) return '#FFD166'
  return '#FF6B6B'
}

export default function HomeTab({ profile, userId, xp, streak, addXp, setTab }) {
  const [briefLoading, setBriefLoading]   = useState(false)
  const [brief, setBrief]                 = useState("")
  const [masteries, setMasteries]         = useState({})
  
  // ── Notifications ───────────────────────────────────────────
  const [pendingBattles, setPendingBattles] = useState([])
  const [lastTab, setLastTab]               = useState(null)

  // ── Mood Check ──────────────────────────────────────────────
  const [mood, setMood] = useState(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('eduvyai_mood') || 'null')
      if (saved && saved.date === new Date().toDateString()) return saved.value
    } catch {}
    return null
  })

  // ── Mera Sawaal (daily problems - 2 per day) ────────────────
  const [dailyQs, setDailyQs]       = useState([])  // Array of 2 questions
  const [dailyAns, setDailyAns]     = useState({})  // { 0: true, 1: false } - track which are revealed
  const [dailyQLoad, setDailyQLoad] = useState(false)
  
  // Track XP awards to prevent duplicates on refresh
  const [dailyXpAwarded, setDailyXpAwarded] = useState(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('eduvyai_dailyq_xp') || '{}')
      // Only use if same date
      if (saved.date === new Date().toDateString()) return saved
    } catch {}
    return { date: new Date().toDateString(), generate: false, show: {} }
  })
  
  const saveDailyXp = (updates) => {
    const newState = { ...dailyXpAwarded, ...updates, date: new Date().toDateString() }
    setDailyXpAwarded(newState)
    localStorage.setItem('eduvyai_dailyq_xp', JSON.stringify(newState))
  }

  // ── Bhool Curve ─────────────────────────────────────────────
  const bhool = useBhoolStats()
  const bhoolDue = bhool.overdue.length + bhool.soon.length

  const subjects = profile.subjects?.length ? profile.subjects : (SUBS[profile.standard] || [])

  // ── Load mastery from backend on mount ─────────────────────
  useEffect(() => {
    if (!userId) return
    apiGetMastery(userId)
      .then(data => { if (data && Object.keys(data).length) setMasteries(data) })
      .catch(() => {})
  }, [userId])

  // ── Load notifications, squad, and last tab ─────────────
  useEffect(() => {
    // Last visited tab from localStorage
    try {
      const saved = localStorage.getItem('eduvyai_last_tab')
      if (saved && saved !== 'home') setLastTab(saved)
    } catch {}

    // Pending Muqabla battles
    apiGetPendingMuqabalaBattles()
      .then(data => { if (data?.battles?.length) setPendingBattles(data.battles) })
      .catch(() => {})
  }, [])

  // Overall mastery average (0% for untouched subjects)
  const masteryValues = subjects.map(s => masteries[s] ?? 0)
  const avgMastery = Math.round(masteryValues.reduce((a, b) => a + b, 0) / (masteryValues.length || 1))

  const saveMood = (m) => {
    setMood(m)
    try { localStorage.setItem('eduvyai_mood', JSON.stringify({ date: new Date().toDateString(), value: m })) } catch {}
  }

  // ── Daily Brief (mood-aware, generated by backend) ──────────────────────
  const generateBrief = async () => {
    const lang = profile.language || 'English'
    
    // Check if already generated today in database for current language
    if (!brief) {
      try {
        const existing = await apiGetDailyContent('brief', lang)
        if (existing?.exists && existing.content) {
          setBrief(existing.content)
          return
        }
      } catch {}
    }
    
    setBriefLoading(true)
    setBrief("")
    
    try {
      const result = await apiGenerateDailyBrief({
        standard: profile.standard,
        board: profile.board || 'CBSE',
        language: lang,
        mood: mood || 'okay',
        subjects: subjects
      })
      
      if (result?.brief) {
        setBrief(result.brief)
        // Only award XP if freshly generated
        if (!result.saved) {
          addXp(5)
        }
      }
    } catch (err) {
      console.error('Brief generation error:', err)
      setBrief(ui.noPlanGenerated || "Could not generate brief. Please try again.")
    }
    
    setBriefLoading(false)
  }

  // Load brief from database on mount and when language changes
  useEffect(() => {
    setBrief('')
    const lang = profile.language || 'English'
    apiGetDailyContent('brief', lang)
      .then(data => { if (data?.exists && data.content) setBrief(data.content) })
      .catch(() => {})
  }, [profile.language])

  // ── Mera Sawaal: daily challenges (2 per day, generated by backend) ─────
  const generateDailyQ = async () => {
    setDailyQLoad(true)
    setDailyQs([])
    setDailyAns({})
    
    // Build full student context like a real teacher would know
    const weakTopics = [...bhool.overdue, ...bhool.soon].map(b => b.concept).slice(0, 5)
    
    try {
      // Call backend with full context - backend builds smart prompt
      const result = await apiGenerateDailyQuestions({
        standard: profile.standard,
        board: profile.board || 'CBSE',
        language: profile.language || 'English',
        mood: mood || 'okay',
        mathMastery: masteries['Mathematics'] || 0,
        scienceMastery: masteries['Science'] || 0,
        weakTopics: weakTopics,
        recentTopics: [] // TODO: track from recent quiz/notebook activity
      })
      
      if (result?.questions?.length > 0) {
        setDailyQs(result.questions.slice(0, 2))
        // Only award XP if freshly generated (not loaded from DB)
        if (!result.saved && !dailyXpAwarded.generate) {
          addXp(5)
          saveDailyXp({ generate: true })
        }
      }
    } catch (err) {
      console.error('Daily questions error:', err)
    }
    
    setDailyQLoad(false)
  }

  // Load daily questions from database on mount and when language changes
  useEffect(() => {
    setDailyQs([])
    setDailyAns({})
    const weakTopics = [...bhool.overdue, ...bhool.soon].map(b => b.concept).slice(0, 5)
    
    apiGenerateDailyQuestions({
      standard: profile.standard,
      board: profile.board || 'CBSE',
      language: profile.language || 'English',
      mood: mood || 'okay',
      mathMastery: masteries['Mathematics'] || 0,
      scienceMastery: masteries['Science'] || 0,
      weakTopics: weakTopics,
      recentTopics: []
    })
      .then(result => {
        if (result?.questions?.length > 0) {
          setDailyQs(result.questions.slice(0, 2))
          if (dailyXpAwarded.show) {
            setDailyAns(dailyXpAwarded.show)
          }
        }
      })
      .catch(() => {})
  }, [mood, masteries, profile.language])

  const greeting = getTimeGreeting(getDisplayLang(profile))
  const ui = li(getDisplayLang(profile))

  return (
    <div className="py-4 px-4 md:px-6 lg:px-8 pb-6">

      {/* ── Mood Check (fresh each day) ───────────────────── */}
      {!mood ? (
        <div className="bg-app-card border border-app-border rounded-[18px] pt-4 px-4 pb-3.5 mb-3.5">
          <div className="text-sm font-bold text-app-text mb-3 flex items-center gap-1.5">
            {ui.moodCheck} <Plant size={16} weight="duotone" className="text-app-green" />
          </div>
          <div className="flex gap-2">
            {[
              { key: "fresh",    icon: "😄", labelKey: "moodFresh",    color: '#00E5A0'  },
              { key: "okay",     icon: "😐", labelKey: "moodOkay",     color: '#7B9CFF'   },
              { key: "stressed", icon: "😟", labelKey: "moodStressed", color: '#FFD166' },
              { key: "tired",    icon: "😴", labelKey: "moodTired",    color: '#6868a0'  },
            ].map(m => (
              <button 
                key={m.key} 
                onClick={() => saveMood(m.key)} 
                className="flex-1 rounded-xl py-2.5 px-1 cursor-pointer font-[Sora,sans-serif] flex flex-col items-center gap-1 border"
                style={{ background: `${m.color}15`, borderColor: `${m.color}30` }}
              >
                <span className="text-[22px]">{m.icon}</span>
                <span className="text-[10px] font-bold" style={{ color: m.color }}>{ui[m.labelKey]?.replace(/^😊|😴|😰|😐\s*/,'') || m.key}</span>
              </button>
            ))}
          </div>
        </div>
      ) : (
        <div className="bg-app-card2 border border-app-border rounded-[14px] py-2.5 px-3.5 mb-3.5 flex items-center justify-between">
          <span className="text-[13px] text-app-muted">
            {mood === "fresh"    && (ui.moodFreshFeedback || "😄 You're fresh — tackle the hard topics today! 🚀")}
            {mood === "okay"     && (ui.moodOkayFeedback || "😐 You're doing okay — steady progress wins. 💪")}
            {mood === "stressed" && (ui.moodStressedFeedback || "😟 You're stressed — quick wins only, no new topics. 🧘")}
            {mood === "tired"    && (ui.moodTiredFeedback || "😴 You're tired — try watching a video or take it easy. 📖")}
          </span>
          <button 
            onClick={() => { setMood(null); localStorage.removeItem('eduvyai_mood') }} 
            className="bg-transparent border-none text-[11px] text-app-muted cursor-pointer font-[Sora,sans-serif]"
          >{ui.change || 'change'}</button>
        </div>
      )}

      {/* ── Hero Card ──────────────────────────────────────── */}
      <div className="bg-gradient-to-br from-[#0b1a2e] via-[#0b1422] to-[#0a1a15] border border-app-green/20 rounded-[20px] pt-5 px-5 pb-4 mb-3.5 relative overflow-hidden">
        {/* Decorative glow */}
        <div className="absolute -top-10 -right-10 w-[120px] h-[120px] bg-[radial-gradient(circle,_#00E5A020,_transparent_70%)] pointer-events-none" />

        <div className="text-[13px] text-app-muted mb-1 flex items-center gap-1.5">
          {greeting.text} <greeting.Icon size={16} weight="fill" style={{ color: greeting.color }} />
        </div>
        <h2 className="text-lg sm:text-[22px] font-black text-app-text m-0 mb-0.5">
          {profile.name || ui.student || "Student"} <HandWaving size={20} weight="fill" className="inline text-app-yellow" />
        </h2>
        <p className="text-xs text-app-muted m-0 mb-4">
          {profile.standard} &nbsp;·&nbsp; {profile.board} &nbsp;·&nbsp; {profile.language}
        </p>

        {/* Stats row */}
        <div className="flex gap-2">
          <StatChip icon={<Lightning size={14} weight="fill" />} value={`${xp} ${ui.xpLabel || 'XP'}`} color={'#FFD166'} />
          <StatChip icon={<Fire size={14} weight="fill" />} value={`${streak} ${ui.streakLabel || 'day streak'}`} color={'#FF6B35'} />
          <StatChip icon={<Brain size={14} weight="fill" />} value={`${avgMastery}% ${ui.avgLabel || 'avg'}`} color={masteryColor(avgMastery)} />
        </div>
      </div>

      {/* ── Daily Brain Brief ─────────────────────────────── */}
      <Section title={<><SunHorizon size={16} weight="duotone" className="inline text-app-orange" /> {ui.dailyBrief?.replace(/^📋\s*/, '') || 'Daily Brain Brief'}</>}>
        {!brief ? (
          <button onClick={generateBrief} disabled={briefLoading} className="primary-btn">
            {briefLoading ? <><Sparkle size={14} weight="fill" className="inline" /> {ui.generating || 'Generating'}…</> : <><Sparkle size={14} weight="fill" className="inline" /> {ui.generateBrief || 'Generate Today\'s Brief'}</>}
          </button>
        ) : (
          <div className="ai-card">
            <p className="text-[13px] text-app-text leading-[1.8] whitespace-pre-wrap m-0">{brief}</p>
          </div>
        )}
      </Section>

      {/* ── Bhool Curve Memory Health ─────────────────────── */}
      {bhoolDue > 0 && (
        <Section title={<><Brain size={16} weight="duotone" className="inline text-app-blue" /> {ui.memoryHealth || 'Memory Health — Spaced Review'}</>}>
          <p className="text-xs text-app-muted mb-3">
            {ui.basedOnScience || 'Based on spaced repetition science — these concepts need review before you forget them'}
          </p>
          <div className="flex gap-2 mb-3.5">
            {bhool.overdue.length > 0 && (
              <div className="flex-1 bg-app-red/10 border border-app-red/30 rounded-xl py-2.5 px-3 text-center">
                <div className="text-xl mb-1"><Circle size={20} weight="fill" className="text-app-red" /></div>
                <div className="text-lg font-black text-app-red">{bhool.overdue.length}</div>
                <div className="text-[10px] text-app-muted mt-0.5">{ui.forgetToday || 'Forget today'}</div>
              </div>
            )}
            {bhool.soon.length > 0 && (
              <div className="flex-1 bg-app-yellow/10 border border-app-yellow/30 rounded-xl py-2.5 px-3 text-center">
                <div className="text-xl mb-1"><Circle size={20} weight="fill" className="text-app-yellow" /></div>
                <div className="text-lg font-black text-app-yellow">{bhool.soon.length}</div>
                <div className="text-[10px] text-app-muted mt-0.5">{ui.dueIn48h || 'Due in 48h'}</div>
              </div>
            )}
            {bhool.fresh.length > 0 && (
              <div className="flex-1 bg-app-green/10 border border-app-green/20 rounded-xl py-2.5 px-3 text-center">
                <div className="text-xl mb-1"><Circle size={20} weight="fill" className="text-app-green" /></div>
                <div className="text-lg font-black text-app-green">{bhool.fresh.length}</div>
                <div className="text-[10px] text-app-muted mt-0.5">{ui.freshLabel || 'Fresh'}</div>
              </div>
            )}
          </div>
          <div className="mb-2.5">
            {bhool.overdue.slice(0, 4).map((item, i) => (
              <div 
                key={i} 
                className="flex items-center gap-2 bg-app-card2 rounded-lg py-1.5 px-2.5 mb-1.5 border border-app-red/20"
              >
                <span className="text-[10px] bg-app-red text-white rounded py-px px-1.5 font-bold">{ui.reviewLabel || 'REVIEW'}</span>
                <span className="text-xs text-app-text font-semibold">{item.concept}</span>
                <span className="text-[11px] text-app-muted ml-auto">{item.subject}</span>
              </div>
            ))}
          </div>
          <button onClick={() => setTab('labs')} className="primary-btn">
            {ui.quickReviseNow || <><Lightning size={14} weight="fill" className="inline" /> Quick Revise Now</>}
          </button>
        </Section>
      )}

      {/* ── Mera Sawaal — 2 Daily Problems ────────────── */}
      <Section title={<><Target size={16} weight="duotone" className="inline text-app-blue" /> {ui.todaysChallenge || "My Questions — Today's Challenge"}</>}>
        <p className="text-xs text-app-muted mb-3">
          {ui.realWorldProblem || 'Two real-world problems using examples from your own state and culture'}
        </p>
        {dailyQs.length === 0 ? (
          <button onClick={generateDailyQ} disabled={dailyQLoad} className="primary-btn">
            {dailyQLoad ? <><DiceFive size={14} weight="fill" className="inline" /> {ui.generating || 'Generating'}…</> : (ui.getTodaysProblem || <><DiceFive size={14} weight="fill" className="inline" /> Get Today's Problems</>)}
          </button>
        ) : (
          <div className="flex flex-col gap-4">
            {dailyQs.map((q, idx) => (
              <div key={idx} className="flex flex-col gap-2.5">
                <div className="bg-app-card2 border border-app-blue/20 rounded-[14px] p-3.5">
                  <div className="flex items-center gap-1.5 mb-2">
                    <span className="text-[10px] font-black text-white bg-app-blue rounded-full w-5 h-5 flex items-center justify-center">
                      {idx + 1}
                    </span>
                    <span className="text-[11px] font-bold text-app-blue bg-app-blue/15 rounded-md py-0.5 px-2">
                      {q.subject}
                    </span>
                    <span className="text-[11px] text-app-muted">{q.concept}</span>
                  </div>
                  <p className="text-sm text-app-text font-semibold leading-relaxed m-0">
                    {q.q}
                  </p>
                </div>
                {!dailyAns[idx] ? (
                  <button 
                    onClick={() => { 
                      setDailyAns(prev => ({ ...prev, [idx]: true }))
                      // Only award XP if not already awarded for this question today
                      if (!dailyXpAwarded.show?.[idx]) {
                        addXp(4)
                        saveDailyXp({ show: { ...dailyXpAwarded.show, [idx]: true } })
                      }
                    }} 
                    className="primary-btn bg-app-yellow/20 border border-app-yellow/40 !text-app-yellow"
                  >
                    {dailyXpAwarded.show?.[idx] ? (ui.showSolution || <><Lightbulb size={14} weight="fill" className="inline" /> Show Solution</>) : (ui.showSolutionXp?.replace('8', '4') || <><Lightbulb size={14} weight="fill" className="inline" /> Show Solution (+4 XP)</>)}
                  </button>
                ) : (
                  <div className="bg-app-green/10 border border-app-green/20 rounded-xl p-3.5">
                    <div className="text-xs font-bold text-app-green mb-1.5 flex items-center gap-1"><CheckCircle size={14} weight="fill" /> {ui.solution || 'Solution'}</div>
                    <p className="text-[13px] text-app-text leading-[1.7] whitespace-pre-wrap m-0">{q.a}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </Section>

      {/* ── Continue Learning ────────────────────────────────── */}
      {lastTab && (
        <Section title={`📚 ${ui.continueLearning || 'Continue Learning'}`}>
          <button
            onClick={() => setTab(lastTab)}
            className="w-full rounded-[14px] py-3.5 px-4 flex items-center justify-between cursor-pointer font-[Sora,sans-serif] border bg-app-card2 border-app-blue/30 hover:border-app-blue/50 transition-colors"
          >
            <div className="flex items-center gap-3">
              <span className="text-xl">
                {lastTab === 'notebook' && <Notebook size={24} weight="duotone" className="text-app-blue" />}
                {lastTab === 'videos' && <FilmSlate size={24} weight="duotone" className="text-app-yellow" />}
                {lastTab === 'labs' && <Flask size={24} weight="duotone" className="text-app-green" />}
                {lastTab === 'squads' && <UsersThree size={24} weight="duotone" className="text-app-blue" />}
                {lastTab === 'mistakes' && <Brain size={24} weight="duotone" className="text-app-red" />}
                {lastTab === 'battles' && <Sword size={24} weight="duotone" className="text-app-orange" />}
                {!['notebook','videos','labs','squads','mistakes','battles'].includes(lastTab) && <MapPin size={24} weight="duotone" className="text-app-muted" />}
              </span>
              <div>
                <div className="text-[13px] font-bold text-app-text">
                  {lastTab === 'notebook' && (ui.notebookTab?.replace(/^📓\s*/, '') || 'Notebook')}
                  {lastTab === 'videos' && (ui.videosTab?.replace(/^🎬\s*/, '') || 'Videos')}
                  {lastTab === 'labs' && (ui.labsTab?.replace(/^🧪\s*/, '') || 'Labs')}
                  {lastTab === 'squads' && (ui.sathiTab?.replace(/^🤝\s*/, '') || 'Study Squads')}
                  {lastTab === 'mistakes' && (ui.bhoolTab?.replace(/^📛\s*/, '') || 'Mistakes')}
                  {lastTab === 'battles' && (ui.muqablaTab?.replace(/^⚔️\s*/, '') || 'Battles')}
                  {lastTab === 'learntv' && (ui.learntvTab?.replace(/^📺\s*/, '') || 'Learn TV')}
                  {!['notebook','videos','labs','squads','mistakes','battles','learntv'].includes(lastTab) && lastTab}
                </div>
                <div className="text-[11px] text-app-muted">{ui.pickUpWhereLeftOff || 'Pick up where you left off'}</div>
              </div>
            </div>
            <span className="text-app-blue text-lg">→</span>
          </button>
        </Section>
      )}

      {/* ── Notifications ────────────────────────────────────── */}
      {pendingBattles.length > 0 && (
        <Section title={<span className="flex items-center gap-1.5"><Bell size={16} weight="fill" className="text-app-yellow" /> {ui.notifications || 'Notifications'}</span>}>
          <div className="flex flex-col gap-2">
            {pendingBattles.slice(0, 3).map((battle, i) => (
              <button
                key={battle.id || i}
                onClick={() => setTab('battles')}
                className="w-full rounded-xl py-3 px-3.5 flex items-center gap-3 cursor-pointer font-[Sora,sans-serif] text-left border bg-app-red/10 border-app-red/30"
              >
                <span className="text-lg"><Sword size={20} weight="duotone" className="text-app-orange" /></span>
                <div className="flex-1">
                  <div className="text-[13px] font-bold text-app-text">
                    {battle.challenger_name || ui.someone || 'Someone'} {ui.challengedYou || 'challenged you!'}
                  </div>
                  <div className="text-[11px] text-app-muted">
                    {battle.subject} • {battle.question_count || 5} {ui.questionsCount || 'questions'}
                  </div>
                </div>
                <span className="text-[11px] font-bold text-app-red bg-app-red/20 rounded-lg py-1 px-2">{ui.accept || 'Accept'}</span>
              </button>
            ))}
          </div>
        </Section>
      )}

    </div>
  )
}

// ── Helpers ──────────────────────────────────────────────────

function getTimeGreeting(lang) {
  const h = new Date().getHours()
  const ui = li(lang)
  if (h < 12) return { text: ui.goodMorning, Icon: Sun, color: '#FFD166' }
  if (h < 17) return { text: ui.goodAfternoon, Icon: CloudSun, color: '#FF9F1C' }
  if (h < 21) return { text: ui.goodEvening, Icon: SunHorizon, color: '#7B9CFF' }
  return { text: ui.lateNightStudy, Icon: Sparkle, color: '#A78BFA' }
}

function StatChip({ icon, value, color }) {
  return (
    <div 
      className="rounded-full py-1.5 px-3 flex items-center gap-1.5 text-xs font-bold flex-1 justify-center border"
      style={{ background: `${color}15`, borderColor: `${color}30`, color }}
    >
      <span>{icon}</span>
      <span>{value}</span>
    </div>
  )
}

function LoadingDots({ label }) {
  return (
    <div className="flex items-center gap-2 py-2.5 justify-center">
      <div className="flex gap-1">
        {[0, 1, 2].map(i => (
          <div 
            key={i} 
            className="w-1.5 h-1.5 rounded-full bg-app-green opacity-60"
            style={{ animation: `pulse 1.2s ease-in-out ${i * 0.2}s infinite` }}
          />
        ))}
      </div>
      <span className="text-xs text-app-muted">{label}</span>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div className="bg-app-card border border-app-border rounded-[18px] p-4 mb-3.5">
      <h3 className="text-sm font-extrabold text-app-text mb-3">{title}</h3>
      {children}
    </div>
  )
}

// Note: primaryBtn, ghostBtn, aiCard classes are defined in index.css
